version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_NAME=drivenow_tz
      - SECRET_KEY=veryveryverysecretkey
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run production

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: drivenow_tz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
